import numpy as np

def fnALFs(rad_colat: np.ndarray, lmax: int) -> np.ndarray: ...
def fnALFs_cache(rad_colat: tuple[float, ...], lmax: int) -> np.ndarray: ...
def fnALF(rad_colat: float, lmax: int) -> np.ndarray: ...
def fnALF_cache(rad_colat: float, lmax: int) -> np.ndarray: ...